/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university.stuff;

import DataBaseAPI.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Hassan
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    DataBase myDB = new DataBase();
    private final String[] stuff = {"", "Management", "Academic", "Security"};
    private final String[] managementJobs = {"Student Affairs", "Graduate Affairs", "Administrative Affairs", "Legal Affairs", "financial affairs"};
    private final String[] academicJobs = {"Profrssor", "Assestant"};
    private final String[] securityJobs = {"Security Manager", "security guard"};
    private final String[] student = {"", "Bachelor", "master", "doctorah"};
    private final String[] bachelorStudent = {"Preparatory", "Civil Engineering", "Communication Engineering", "Mechatronics Engineering", "Architecture Engineering", "Power Engineering"};
    private final String[] levelPreparatoryStudent = {"1"};
    private final String[] levelSpecializedStudent = {"2", "3", "4", "5"};

    public static int createdStudentNum = 0;
    public static int createdStuffNum = 0;
    private String whoRegister;

    public Register(String whoRegister) {

        this.whoRegister = whoRegister;
        initComponents();

        if (whoRegister.equals("empolyee")) {
            jLabel3.setText("Department");
            departmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(stuff));
            jLabel4.setText("Job");
            jLabel13.setVisible(false);
            levelComboBox.setVisible(false);
        } else if (whoRegister.equals("student")) {
            jLabel3.setText("Qualification");
            departmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(student));
            jLabel4.setText("Specialization");
        }
        if (whoRegister.equals("empolyee")) {
            createdStuffNum++;
            System.out.println("createdStuffNum  " + createdStuffNum);
        } else {
            createdStudentNum++;
            System.out.println("createdStudentNum  " + createdStudentNum);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        departmentComboBox = new javax.swing.JComboBox<>();
        jobComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        birthDayTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mobileTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        levelComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        jLabel1.setText("Login Code");

        jLabel2.setText("Password");

        jLabel3.setText("Department");

        usernameTextField.setText("1");

        passwordField.setText("password");

        departmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Management", "Academic", "Security" }));
        departmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentComboBoxActionPerformed(evt);
            }
        });

        jobComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Job");

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Full Name");

        nameTextField.setText("Amro Emad Askar");

        jLabel6.setText("National ID");

        idTextField3.setText("29901011302568");

        jLabel7.setText("Address");

        addressTextField.setText("minya alqamh / sharkia");

        jLabel8.setText("Birth Day");

        birthDayTextField.setText("1999-01-01");

        emailTextField.setText("amraskar543@gmail.com");

        jLabel9.setText("Email");

        mobileTextField.setText("01069163037");

        jLabel10.setText("Mobile");

        jLabel11.setText("Personal Informations");

        jLabel12.setText("Stuff Inforamations");

        jLabel13.setText("Level");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(jLabel12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registerButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(birthDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mobileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(departmentComboBox, 0, 265, Short.MAX_VALUE)
                                        .addComponent(passwordField)
                                        .addComponent(usernameTextField)
                                        .addComponent(jobComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(levelComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(idTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(birthDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(mobileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(departmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(registerButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void departmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentComboBoxActionPerformed
        if (departmentComboBox.getSelectedItem().equals("Management")) {
            jobComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(managementJobs));

        } else if (departmentComboBox.getSelectedItem().equals("Academic")) {
            jobComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(academicJobs));

        } else if (departmentComboBox.getSelectedItem().equals("Security")) {
            jobComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(securityJobs));

        } else if (departmentComboBox.getSelectedItem().equals("Bachelor")) {
            jobComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(bachelorStudent));
        }
    }//GEN-LAST:event_departmentComboBoxActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        if (isAnyFieldEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Fill all fields");
        } else if (isUserExist() == 1) {
            JOptionPane.showMessageDialog(this, "Username already exists");
        } else if (isUserExist() == 2) {
            JOptionPane.showMessageDialog(this, "User Code is numbers only");
        } else if (isnationalIDExist() == 1) {
            JOptionPane.showMessageDialog(this, "National ID already exists");
        } else if (isnationalIDExist() == 2) {
            JOptionPane.showMessageDialog(this, "National Id is numbers only");
        } else if (isEmailExist() == 1) {
            JOptionPane.showMessageDialog(this, "Email already exists");
        } else if (isEmailExist() == 2) {
            JOptionPane.showMessageDialog(this, "That's not email");
        } else if (isMobileExist() == 1) {
            JOptionPane.showMessageDialog(this, "Mobile already exists");
        } else if (isMobileExist() == 2) {
            JOptionPane.showMessageDialog(this, "Mobile is numbers only");
        } else if (isJobNotSelected()) {
            JOptionPane.showMessageDialog(this, "Please Select Department");
        } else if (!birthDayTextField.getText().matches("^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$")) {
            JOptionPane.showMessageDialog(this, "Enter Birth Day like yyyy-mm-dd like 1997-06-15 ");
        } else {
            try {
                myDB.connectToDataBase();

                myDB.insertDataIntoAllColumns("user", "" + usernameTextField.getText() + " "
                        + ", '" + passwordField.getText() + "' , '" + whoRegister + "'");

                if (whoRegister.equals("empolyee")) {
                    myDB.connectToDataBase();
                    myDB.insertDataIntoAllColumns("staff", "" + usernameTextField.getText() + " "
                            + ", '" + departmentComboBox.getSelectedItem() + "' "
                            + ", '" + jobComboBox.getSelectedItem() + "' ");

                } else if (whoRegister.equals("student")) {
                    myDB.connectToDataBase();
                    myDB.insertDataIntoAllColumns("student", "'" + usernameTextField.getText() + "' "
                            + ", '" + departmentComboBox.getSelectedItem() + "' "
                            + ", '" + jobComboBox.getSelectedItem() + "' "
                            + ", " + levelComboBox.getSelectedItem() + " ");

                }
                myDB.connectToDataBase();
                myDB.insertDataIntoAllColumns("personal_info", "'" + usernameTextField.getText() + "' "
                        + ", '" + nameTextField.getText() + "' " + ", '" + idTextField3.getText() + "' "
                        + ", '" + birthDayTextField.getText() + "' " + ", '" + addressTextField.getText() + "' "
                        + ", '" + emailTextField.getText() + "' " + ", '" + mobileTextField.getText() + "' ");

                JOptionPane.showMessageDialog(this, "Succesfully Added");

            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            } finally {
                try {
                    myDB.closeDataBaseConnection();
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void jobComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobComboBoxActionPerformed
        if (jobComboBox.getSelectedItem().equals("Preparatory")) {
            levelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(levelPreparatoryStudent));
        } else if (!jobComboBox.getSelectedItem().equals("Preparatory")) {
            levelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(levelSpecializedStudent));
        }
    }//GEN-LAST:event_jobComboBoxActionPerformed
    private boolean isAnyFieldEmpty() {
        if (nameTextField.getText().isEmpty() || idTextField3.getText().isEmpty() || addressTextField.getText().isEmpty()
                || birthDayTextField.getText().isEmpty() || emailTextField.getText().isEmpty() || mobileTextField.getText().isEmpty()
                || usernameTextField.getText().isEmpty() || passwordField.getText().isEmpty()) {
            return true;
        }
        return false;
    }

    private int isUserExist() {
        if (usernameTextField.getText().matches("[0-9]+")) {
            try {
                myDB.connectToDataBase();
                for (Table.Column column : myDB.getColumnsData("personal_info", "id")) {

                    for (String info : column.getColumnsDatas()) {
                        if (info.equals(usernameTextField.getText())) {
                            return 1;
                        }
                    }
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            } finally {
                try {
                    myDB.closeDataBaseConnection();
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        } else {
            return 2;
        }
        return 0;
    }

    private int isnationalIDExist() {
        if (idTextField3.getText().matches("[0-9]+")) {
            try {
                myDB.connectToDataBase();
                for (Table.Column column : myDB.getColumnsData("personal_info", "national_id")) {

                    for (String info : column.getColumnsDatas()) {
                        if (info.equals(idTextField3.getText())) {
                            return 1;
                        }
                    }
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            } finally {
                try {
                    myDB.closeDataBaseConnection();
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        } else {
            return 2;
        }
        return 0;
    }

    private int isEmailExist() {
        //if (emailTextField.getText().matches("[0-9]+")) {
        try {
            myDB.connectToDataBase();
            for (Table.Column column : myDB.getColumnsData("personal_info", "email")) {

                for (String info : column.getColumnsDatas()) {
                    if (info.equals(emailTextField.getText())) {
                        return 1;
                    }
                }
            }
        } catch (SQLException ex) {

            System.out.println(ex.getMessage());
        } finally {
            try {
                myDB.closeDataBaseConnection();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
//        } else {
//            return 2;
//        }
        return 0;
    }

    private int isMobileExist() {
        if (mobileTextField.getText().matches("[0-9]+")) {
            try {
                myDB.connectToDataBase();
                for (Table.Column column : myDB.getColumnsData("personal_info", "mobile")) {
                    for (String info : column.getColumnsDatas()) {
                        if (info.equals(mobileTextField.getText())) {
                            return 1;
                        }
                    }
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            } finally {
                try {
                    myDB.closeDataBaseConnection();
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        } else {
            return 2;
        }
        return 0;
    }

    private boolean isJobNotSelected() {
        if (departmentComboBox.getSelectedItem().equals("")) {
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField birthDayTextField;
    private javax.swing.JComboBox<String> departmentComboBox;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField idTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> jobComboBox;
    private javax.swing.JComboBox<String> levelComboBox;
    private javax.swing.JTextField mobileTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
